name: Static Analysis for C++ Code

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy cppcheck g++

      - name: Compile All C++ Files
        run: |
          g++ -Wall -Werror -o main *.cpp

      - name: Run clang-tidy for Code Refactoring Suggestions
        run: |
          clang-tidy *.cpp -- -std=c++17

      - name: Run cppcheck for Static Analysis
        run: |
          cppcheck --enable=all --inconclusive --std=c++17 --force .
